python3 train.py \
--dataset-config stable_audio_tools/configs/dataset_configs/anime_dataset_txt2audio.json \
--model-config stable_audio_tools/configs/model_configs/txt2audio/stable_audio_open_1_0_anime_dit_only.json \
--pretrained-ckpt-path /home/ndrw1221/lab-projects/stable-audio-tools/stable-audio-open-1.0/model.ckpt \
--pretransform-ckpt-path vae_unwrap.ckpt \
--save-dir output \
--name sao-anime \
--run-name dit_with_ft_vae \
--checkpoint-every 10000 \
--batch-size 8 \
