python3 train.py \
--dataset-config stable_audio_tools/configs/dataset_configs/audio_prompt/musiccocoa_emb+text.json \
--model-config stable_audio_tools/configs/model_configs/txt2audio/sao_audio_prompt/stable_audio_open_1_0_audio_prompt+text.json \
--ckpt-path output/sao-anime-audio-prompt/musiccoca-emb+text/checkpoints/epoch=842-step=240000.ckpt \
--save-dir /mnt/gestalt/home/ndrw1221/stable_audio_tools_output \
--name sao-anime-audio-prompt \
--run-name musiccoca-emb+text \
--checkpoint-every 40000 \
--batch-size 8 \
