python bulk_inference.py \
--model-config stable-audio-open-1.0/model_config.json \
--ckpt-path stable-audio-open-1.0/model.ckpt \
--prompts /mnt/gestalt/home/ndrw1221/lab-projects/new-anime-dataset-preprocess/new_anime_eval_prompts.txt \
--output-dir evaluation_outputs/sao_1_0 \
--steps 150 \
--cfg-scale 7.0 \
--batch-size 8 \
--seconds-start 20 \
--seconds-total 180 \
--include-seed-in-filename \
--save-metadata \